{{- if and .Values.ingress.enabled .Values.website.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "acp.fullname" . }}-website
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "acp.labels" . | nindent 4 }}
    app.kubernetes.io/component: website
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.website.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.website.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "acp.fullname" . }}-website
                port:
                  number: {{ .Values.website.service.port }}
{{- end }}
