security:
    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            pattern: ^/
            security: false

    access_control: []
