services:
  slides:
    build:
      context: .
      dockerfile: docker/slides/Dockerfile
    labels:
      - traefik.enable=true
      - traefik.docker.network=ai-community-platform_dev-edge
      - traefik.http.routers.slides.rule=Host(`slides.ai-community-platform.org`)
      - traefik.http.routers.slides.entrypoints=web
      - traefik.http.services.slides.loadbalancer.server.port=80
    networks:
      - dev-edge
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
