<?php

declare(strict_types=1);

namespace App\Service;

use Psr\Log\LoggerInterface;

final class GitHubService
{
    public function __construct(
        private readonly LoggerInterface $logger,
        private readonly string $repoRoot,
        private readonly string $ghToken,
    ) {
    }

    public function createPr(int $taskId, string $branch, string $title): ?string
    {
        if ('' === $this->ghToken) {
            $this->logger->info('GH_TOKEN not set, skipping PR creation');

            return null;
        }

        $this->exec(\sprintf(
            'git -C %s push origin %s',
            escapeshellarg($this->repoRoot),
            escapeshellarg($branch),
        ));

        $body = "Pipeline task #{$taskId}\n\nGenerated by dev-agent pipeline.";

        $output = $this->exec(\sprintf(
            'GH_TOKEN=%s gh pr create --repo %s --head %s --title %s --body %s 2>&1',
            escapeshellarg($this->ghToken),
            escapeshellarg($this->getRepoSlug()),
            escapeshellarg($branch),
            escapeshellarg($title),
            escapeshellarg($body),
        ));

        if (preg_match('|https://github\.com/[^/]+/[^/]+/pull/\d+|', $output, $m)) {
            return $m[0];
        }

        $this->logger->warning('Could not parse PR URL from gh output', ['output' => $output]);

        return null;
    }

    private function getRepoSlug(): string
    {
        $output = $this->exec(\sprintf(
            'git -C %s remote get-url origin 2>/dev/null',
            escapeshellarg($this->repoRoot),
        ));

        if (preg_match('|github\.com[:/](.+?)(?:\.git)?$|m', $output, $m)) {
            return $m[1];
        }

        return 'nmdimas/ai-community-platform';
    }

    private function exec(string $command): string
    {
        $output = [];
        $exitCode = 0;
        exec($command, $output, $exitCode);

        $result = implode("\n", $output);

        if (0 !== $exitCode) {
            throw new \RuntimeException("Command failed (exit {$exitCode}): {$result}");
        }

        return $result;
    }
}
